chore: new service system (retro-compatible)
SocialGouv/mano pull request #1141
Opened 2022-12-30 14:34 UTC by rap2hpoutre

2023-01-02 09:58 UTC, arnaudambro commented
je sais que c'est pas encore à review mais pourquoi tu ne fais pas de migration ?

2023-01-09 16:48 UTC, rap2hpoutre commented
> je sais que c'est pas encore à review mais pourquoi tu ne fais pas de migration ?

Je pense qu'on peut continuer à limiter les moments de flottements où les gens enregistrent dans l'ancien système alors que le nouveau système a été livré. 

Je trouve aussi qu'on voit mieux si on n'a rien cassé en testant sur un système rétrocompatible : "les tests auto fonctionnent toujours, les tests en local fonctionnent toujours avec des vieilles bases, bon tout baigne, le système fait sa transition douce".

Ça n'a pas un grand impact de continuer à regarder dans les rapports pour voir s'il y a des infos sur les services et de les merge. Il y a finalement peu de ligne de code (tout est dans un useEffect) et les variables s'appellent legacy.

Moi j'aime bien avancer pas à pas comme on fait en ce moment, difficile de voir si ça nous fait diminuer le "un commit" puis "trois commits de fix", on verra un peu plus tard.

2023-01-10 09:00 UTC, arnaudambro commented
j'ai réussi à avoir une erreur

```
UniqueConstraintError [SequelizeUniqueConstraintError]: Validation error
    at Query.formatError (/Users/arnaudambroselli/Pro/2020-07-033_Selego_Mano/mano/api/node_modules/sequelize/lib/dialects/postgres/query.js:344:18)
    at Query.run (/Users/arnaudambroselli/Pro/2020-07-033_Selego_Mano/mano/api/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/arnaudambroselli/Pro/2020-07-033_Selego_Mano/mano/api/node_modules/sequelize/lib/sequelize.js:619:16
    at async PostgresQueryInterface.upsert (/Users/arnaudambroselli/Pro/2020-07-033_Selego_Mano/mano/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:805:12)
    at async Function.upsert (/Users/arnaudambroselli/Pro/2020-07-033_Selego_Mano/mano/api/node_modules/sequelize/lib/model.js:2482:20) {
  errors: [
    ValidationErrorItem {
      message: 'service must be unique',
      type: 'unique violation',
      path: 'service',
      value: '2cc',
      origin: 'DB',
      instance: [Service],
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    },
    ValidationErrorItem {
      message: 'date must be unique',
      type: 'unique violation',
      path: 'date',
      value: '2023-01-10',
      origin: 'DB',
      instance: [Service],
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    },
    ValidationErrorItem {
      message: 'team must be unique',
      type: 'unique violation',
      path: 'team',
      value: '00000000-5f5a-8b93-3b5a-1cfb37006fda',
      origin: 'DB',
      instance: [Service],
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    }
  ],
  fields: {
    service: '2cc',
    date: '2023-01-10',
    team: '00000000-5f5a-8b93-3b5a-1cfb37006fda'
  },
  parent: error: duplicate key value violates unique constraint "Service_service_date_team_key"
      at Parser.parseErrorMessage (/Users/arnaudambroselli/Pro/2020-07-033_Selego_Mano/mano/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/arnaudambroselli/Pro/2020-07-033_Selego_Mano/mano/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/arnaudambroselli/Pro/2020-07-033_Selego_Mano/mano/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/arnaudambroselli/Pro/2020-07-033_Selego_Mano/mano/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:527:28)
      at Socket.emit (node:domain:537:15)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 287,
    severity: 'ERROR',
    code: '23505',
    detail: 'Key (service, date, team)=(2cc, 2023-01-10, 00000000-5f5a-8b93-3b5a-1cfb37006fda) already exists.',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: 'mano',
    table: 'Service',
    column: undefined,
    dataType: undefined,
    constraint: 'Service_service_date_team_key',
    file: 'nbtinsert.c',
    line: '656',
    routine: '_bt_check_unique',
    sql: 'INSERT INTO "mano"."Service" ("_id","date","service","count","team","organisation","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT ("_id") DO UPDATE SET "team"=EXCLUDED."team","date"=EXCLUDED."date","service"=EXCLUDED."service","organisation"=EXCLUDED."organisation","count"=EXCLUDED."count","updatedAt"=EXCLUDED."updatedAt" RETURNING "_id","date","service","count","team","organisation","createdAt","updatedAt";',
    parameters: [
      'c0b3b18f-b1db-496a-a1b4-ead6abc0bddd',
      '2023-01-10',
      '2cc',
      9,
      '00000000-5f5a-8b93-3b5a-1cfb37006fda',
      '00000000-5f5a-89e2-2e60-88fa20cc50bf',
      '2023-01-10 09:59:26.559 +01:00',
      '2023-01-10 09:59:26.559 +01:00'
    ]
  },
  original: error: duplicate key value violates unique constraint "Service_service_date_team_key"
      at Parser.parseErrorMessage (/Users/arnaudambroselli/Pro/2020-07-033_Selego_Mano/mano/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/arnaudambroselli/Pro/2020-07-033_Selego_Mano/mano/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/arnaudambroselli/Pro/2020-07-033_Selego_Mano/mano/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/arnaudambroselli/Pro/2020-07-033_Selego_Mano/mano/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:527:28)
      at Socket.emit (node:domain:537:15)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 287,
    severity: 'ERROR',
    code: '23505',
    detail: 'Key (service, date, team)=(2cc, 2023-01-10, 00000000-5f5a-8b93-3b5a-1cfb37006fda) already exists.',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: 'mano',
    table: 'Service',
    column: undefined,
    dataType: undefined,
    constraint: 'Service_service_date_team_key',
    file: 'nbtinsert.c',
    line: '656',
    routine: '_bt_check_unique',
    sql: 'INSERT INTO "mano"."Service" ("_id","date","service","count","team","organisation","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT ("_id") DO UPDATE SET "team"=EXCLUDED."team","date"=EXCLUDED."date","service"=EXCLUDED."service","organisation"=EXCLUDED."organisation","count"=EXCLUDED."count","updatedAt"=EXCLUDED."updatedAt" RETURNING "_id","date","service","count","team","organisation","createdAt","updatedAt";',
    parameters: [
      'c0b3b18f-b1db-496a-a1b4-ead6abc0bddd',
      '2023-01-10',
      '2cc',
      9,
      '00000000-5f5a-8b93-3b5a-1cfb37006fda',
      '00000000-5f5a-89e2-2e60-88fa20cc50bf',
      '2023-01-10 09:59:26.559 +01:00',
      '2023-01-10 09:59:26.559 +01:00'
    ]
  },
  sql: 'INSERT INTO "mano"."Service" ("_id","date","service","count","team","organisation","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT ("_id") DO UPDATE SET "team"=EXCLUDED."team","date"=EXCLUDED."date","service"=EXCLUDED."service","organisation"=EXCLUDED."organisation","count"=EXCLUDED."count","updatedAt"=EXCLUDED."updatedAt" RETURNING "_id","date","service","count","team","organisation","createdAt","updatedAt";'
}
```

2023-01-10 09:09 UTC, arnaudambro commented
[FACULTATIF]

https://user-images.githubusercontent.com/31724752/211508561-73953083-d910-47ff-a2b4-a52501f05d38.mov

Je me dis que si sur nos machines puissantes en localhost on a un "décalage" d'affichage des données comme ça, les utilisateurs vont l'avoir encore plus en production...

2023-01-10 09:10 UTC, arnaudambro commented on api/src/controllers/service.js
> +        replacements: { date, team: team.includes(",") ? team.split(",") : [team], organisation },
note pour moi pour discuter mais: pourquoi il faut toujours faire cette méthode avec SQL et pas de template string genre 
```
`where date_trunc('month', "date") = ${date}`
```

2023-01-10 09:12 UTC, arnaudambro commented on api/src/controllers/service.js
> +      .catch((e) => {
pas besoin du `catch` ici puisque si ça plante ça sera capté par le `catchErrors` je pense

2023-01-10 09:14 UTC, arnaudambro commented on dashboard/src/components/IncrementorSmall.js
> +        if (res.ok) onUpdated(res.data.count);
else setValue(
```suggestion
        if (res.ok) onUpdated(res.data.count);
        else setValue(initialValue)
```

2023-01-10 09:28 UTC, arnaudambro requested changes
- Il manque le changement dans les stats
- Je pense qu'on ne pourra pas échapper à la migration, retro-compatibilité ou pas... parce que  là en l'occurence, ce n'est pas réellement rétro-compatible : si quelqu'un a une version 1 du dashboard qui n'utilise pas les nouveaux services del a version 2, il ne sera pas conscient que ces services existent donc il y aura aussi une erreur

2023-01-10 10:09 UTC, rap2hpoutre commented on api/src/controllers/service.js
> +        replacements: { date, team: team.includes(",") ? team.split(",") : [team], organisation },
Parce que sinon on peut faire une injection. `date` peut valoir `'' or 1=1`. On donne donc la possibilité à l'utilisateur d'écrire du code et de l''exécuter sur le serveur. C'est comme si côté front on permettait directement d'écrire du code à nos utilisateurs: `<div dangerouslySetInnerHTML={data} />` ils peuvent péter la page.
Là on leur offrirait la possibilité de détruire la base de données. Ou de faire une opération couteuse. On ne veut pas laisser les gens écrire du code, on veut prendre les valeurs qu'ils nous donnent.


<img width="689" alt="Capture d’écran 2023-01-10 à 11 07 40" src="https://user-images.githubusercontent.com/1575946/211522286-cbdecfb9-12d6-470b-bf3f-b63b2d0e672e.png">

```
where date_trunc('month', "date") = ${date}
```

2023-01-10 15:02 UTC, rap2hpoutre commented on dashboard/src/components/ReceptionService.js
> +    // Init services for a team. We need to fetch services from legacy report and database and merge them.
Plus tard

2023-01-10 15:04 UTC, arnaudambro commented on dashboard/src/components/IncrementorSmall.js
> +        if (res.ok) onUpdated(res.data.count);
bah si t'as pas réussi à MAJ pour je ne sais quelle raison, tu veux pas dire à l'utilisateur que ça a bien marché non ?

2023-01-11 10:15 UTC, arnaudambro commented
mmm y'a un truc que j'explique pas:
sur https://dashboard-mano-service-new.dev.fabrique.social.gouv.fr/stats quel que soit la période demandée c'est toujours les même stats
mais en local ça a l'air de marcher

2023-01-12 11:10 UTC, arnaudambro approved these changes

2023-01-12 11:34 UTC, merged