feat: help on each stat element
SocialGouv/mano pull request #1194
Opened 2023-01-13 17:16 UTC by arnaudambro

- ongoing
- feat: help on each stat element

2023-01-16 19:26 UTC, marioonb commented on dashboard/src/scenes/stats/General.js
> +          help={`Moyenne d'actions créées par "personne suivies" dans la période définie.\n\nSi aucune période n'est définie, on considère la totalité des actions par rapport à la totalité des person
help={`Moyenne d'actions créées par "personnes suivies" dans la période définie.\n\nSi aucune période n'est définie, on

2023-01-16 19:27 UTC, marioonb commented on dashboard/src/scenes/stats/General.js
> +          help={`Moyenne d'actions créées par "personne suivies" <b>pour lesquelles au moins une action a été créée</b> dans la période définie.\n\nSi aucune période n'est définie, on considère la to
help={`Moyenne d'actions créées par "personnes suivies" <b>pour lesquelles au moins une action a été créée</b> dans la période

2023-01-16 19:32 UTC, marioonb requested changes
Il y a aussi une coquille ici :  (hommes rencontrés et non rencontrées)

![Capture d’écran 2023-01-16 à 20 29 57](https://user-images.githubusercontent.com/39462001/212753529-f636dc77-8e38-4698-8f72-c67c80a4c821.png)

Mais cela ne semble pas avoir été modifié dans cette PR

2023-01-17 09:24 UTC, arnaudambro commented
> (hommes rencontrés et non rencontrées)

ah oui tu as raison !
elle est là depuis très très longtemps celle-là...
en fait c'est un champs "champs custo", et c'est un champ par défaut.
Mais tu as raison, il faudra le modifier !

2023-01-17 09:28 UTC, merged