fix(dashboard): cut too long words without spaces delete modal
SocialGouv/mano pull request #1236
Opened 2023-01-23 14:38 UTC by marioonb

2023-01-23 14:57 UTC, arnaudambro requested changes

2023-01-23 14:57 UTC, arnaudambro commented on dashboard/src/components/DeleteButtonAndConfirmModal.js
> +          <p className="tw-break-all tw-flex tw-text-center">
mm il manque une propriété je pense

<img width="776" alt="image" src="https://user-images.githubusercontent.com/31724752/214071578-7e277edf-2a0b-4a87-bf68-06a4d49dd86d.png">

2023-01-23 15:26 UTC, marioonb commented on dashboard/src/components/DeleteButtonAndConfirmModal.js
> +          <p className="tw-break-all tw-flex tw-text-center">
OOPS...

2023-01-24 09:23 UTC, arnaudambro approved these changes

2023-01-24 09:30 UTC, merged