fix(dashboard): noms d'action ou noms de personne trop longs dans l'a…
SocialGouv/mano pull request #1266
Opened 2023-01-28 12:33 UTC by marioonb

…ffichage de l'agenda

2023-01-30 09:56 UTC, rap2hpoutre approved these changes
Super !

2023-01-30 10:14 UTC, rap2hpoutre requested changes
A fix pour pas couper tous les mots au milieu

2023-02-07 09:52 UTC, arnaudambro approved these changes

2023-02-07 09:56 UTC, arnaudambro commented
approved ! mais du coup je me suis rendu compte que c'était pas parfait ailleurs
mais c'est peut-être dans une autre PR, ou prévu, en tout cas j'ai l'impression que vous avez fait le tour avec Raph

celle-là tu peux merger !

<img width="298" alt="image" src="https://user-images.githubusercontent.com/31724752/217212019-58402a8f-9d0c-40b3-a408-77e35903d58b.png">

2023-02-07 09:57 UTC, arnaudambro commented
merde j'ai fait n'importe quoi avec mon rebase 😭

2023-02-07 14:20 UTC, closed without merging