fix(dashboard): retour à ligne des noms de territoire trop longs dans la liste des te…
SocialGouv/mano pull request #1267
Opened 2023-01-28 12:41 UTC by marioonb

…rritoires

2023-01-30 09:57 UTC, rap2hpoutre approved these changes

2023-01-30 10:15 UTC, rap2hpoutre requested changes
Pareil

2023-02-06 12:24 UTC, marioonb commented
PAs top mais pour enfin passer à autre chose en attendant... J'en ai profité pour supprimer Create style

2023-02-07 10:27 UTC, arnaudambro commented on dashboard/src/scenes/territory/list.js
> +                <div style={{overflowWrap: 'anywhere'}}>
dans l'idéal, même si je sais que là y'en a partout (c'est une dette dont on a hérité), on veut éviter les `style={{ }}` parce que
- `We recommend to only use the style attribute when your styles depend on JavaScript variables.` -> https://beta.reactjs.org/reference/react-dom/components/common#applying-css-styles
- pour être cohérent au maximum avec l'utilisation de tailwind (même si Tailwind ce sont des classes prédéfinies et que là c'est pas le cas...)
- parce que c'est moche d'avoir les deux, je trouve (ce n'est que mon avis)
- parce que pour beaucoup, ce n'est pas une bonne pratique d'avoir des objets "inline", c'est-à-dire définis à la volée, parce que ça peut affecter les performances (NA dans notre cas je pense, mais bon à avoir en tête quand même)


ce n'est qu'une suggestion, j'accepte qu'elle soit 🥊 bien sûr

```suggestion
                <div className="[overflow-wrap:anywhere]">
```

2023-02-07 10:32 UTC, arnaudambro commented on dashboard/src/scenes/territory/list.js
> +                <div style={{overflowWrap: 'anywhere'}}>
on peut aussi modifier la config tailwind pour rajouter une classe plus propre aussi, si on veut - mais bon, moi je préfère ça

2023-02-07 14:34 UTC, closed without merging