fix(dashboard): noms de services trop longs dans l'onglet Accueil de la page statistique
SocialGouv/mano pull request #1323
Opened 2023-02-11 13:13 UTC by marioonb

Avant : 

![Capture d’écran 2023-02-11 à 13 59 46](https://user-images.githubusercontent.com/39462001/218259896-78c756a7-9069-40fb-874d-570a520f9652.png)

Après : 

![Capture d’écran 2023-02-11 à 14 08 23](https://user-images.githubusercontent.com/39462001/218259911-118d3fbb-adb2-4788-b33b-0d32acb54f0d.png)

2023-02-13 13:32 UTC, arnaudambro commented
je check ça
si tu peux mettre des screenshot plein écran la prochaine fois, ça serait top pour moi, comme ça je sais d'où tu as accédé aux services!

2023-02-13 13:37 UTC, arnaudambro requested changes
<img width="754" alt="image" src="https://user-images.githubusercontent.com/31724752/218471956-a6bd3737-75c1-43c6-8322-d04f494a523d.png">
<img width="754" alt="image" src="https://user-images.githubusercontent.com/31724752/218472030-36c84b0a-2f13-4375-9707-83a5129ea2d8.png">

ça a planté 
- les chiffres qui sont mal affichés
- l'affichage du camembert 😳 va comprendre...

je me pencherait vers un `max-width` sur le tableau ! peut-être

2023-02-15 10:03 UTC, marioonb commented
Oups... J'ai enlevé l'id au niveau de return.... ca explique le problème de camembert

2023-02-15 13:29 UTC, arnaudambro approved these changes

2023-02-15 14:44 UTC, merged