fix(dashboard): mauvaise date de derniere interaction pas lors d'un changement de clé
SocialGouv/mano pull request #1348
Opened 2023-02-23 20:27 UTC by marioonb

2023-02-27 11:39 UTC, arnaudambro commented on dashboard/src/recoil/selectors.js
> +        lastUpdateCheckForGDPR: person.createdAt,
est-ce qu'on regarderait pas dans l'historique ?

2023-02-27 12:32 UTC, arnaudambro commented on dashboard/src/recoil/selectors.js
> +        lastUpdateCheckForGDPR: person.createdAt,
je pense que c'est faisable - regarder la date de la dernière (ou la première je ne sais plus) entrée

2023-02-27 12:32 UTC, arnaudambro approved these changes

2023-02-27 21:11 UTC, marioonb commented
J'ai ajouté une date de dernière interaction si changement dans le dossier en passant par ton idée d'historique. Par contre, il faut que je vois pour une date lors d'ajout de docs car je ne visualise pas comment ils sont stockés pour le moment.

2023-02-28 12:10 UTC, arnaudambro requested changes

2023-02-28 12:10 UTC, arnaudambro commented on dashboard/src/recoil/selectors.js
> +      if (person.history[person.history.length - 1].date > personsObject[person._id].lastUpdateCheckForGDPR) {
tu peux retirer ce check: si une personne a un historique, la date est forcément supérieure à la date `createdAt`

2023-02-28 12:10 UTC, arnaudambro commented on dashboard/src/recoil/selectors.js
> +      console.log(person.documents);
```suggestion
```

2023-02-28 12:10 UTC, arnaudambro commented on dashboard/src/recoil/selectors.js
>        }
```suggestion
      }
```

2023-02-28 12:10 UTC, arnaudambro commented on dashboard/src/recoil/selectors.js
>        }
tu as retiré cette accolade, c'est pour ça que les tests plantent je pense

2023-02-28 14:31 UTC, marioonb commented on dashboard/src/recoil/selectors.js
> +      console.log(person.documents);
En effet... J'ai enlevé l'autosave et j'ai pas du faire mon changement !! Merci

2023-03-01 12:49 UTC, arnaudambro approved these changes

2023-03-01 14:27 UTC, merged