feat: imprimer une modale de plusieurs pages
SocialGouv/mano pull request #1360
Opened 2023-02-27 13:27 UTC by arnaudambro

J'ai un user qui a un bug : il va dans stats --> personne suivie --> clique un les "non renseignés" de nimporte quel camembert --> fait ctrl+P pour sortir un pdf et le pdf qui sort ya que le première page sur toutes les pages.

2023-03-09 15:57 UTC, arnaudambro commented
Une des PR la moins rentable...

Temps passé: M/L
Apport utilisateur: XS
Relouitude: XL

2023-03-09 16:10 UTC, rap2hpoutre commented on dashboard/src/scenes/stats/Persons.js
> +    }, 100);
Mais euh. Quel avantage par rapport à zéro ? On attend quoi qui arbitrairement doit passer dans l'event loop puis mettre entre 0 et 100 ms?

2023-03-12 07:43 UTC, arnaudambro commented on dashboard/src/scenes/stats/Persons.js
> +    }, 100);
j'ai testé une fois avec 0 ça n'a pas marché, puis avec 100 ça a marché...

mais je vais réessayer pour voir

2023-03-14 10:20 UTC, rap2hpoutre requested changes
Mince, moi ça ne marche pas. Quand je clique sur imprimer, ça fait un flash rapide de l'écran et ça ne fait rien (aka ça n'imprime pas). J'ai changé le timeout à 1 seconde et ça ne change rien. Pourquoi on ne ferait pas juste un export excel, ce serait plus simple non ? Je demande à Nathan !

2023-03-14 10:20 UTC, rap2hpoutre commented on dashboard/src/scenes/stats/Persons.js
> +  console.log({ title });
```suggestion
```

2023-03-16 08:17 UTC, rap2hpoutre commented
PS: Nathan est ouvert à un export Excel

2023-03-20 12:58 UTC, closed without merging