fix(dashboard): titre et selecteur de l'ajout d'action dans les cpt rendu qui etait a la mauvaise date
SocialGouv/mano pull request #1396
Opened 2023-03-09 15:09 UTC by marioonb

- date dans le titre "créer une nouvelle action faite le ...." qui ne correspondait pas a la date du compte rendu actuellement ouvert.
- date dans le selecteur n'était pas mis sur la date du compte rendu actuellement ouvert

2023-03-13 16:36 UTC, rap2hpoutre approved these changes

2023-03-22 08:50 UTC, arnaudambro commented on dashboard/src/scenes/report/view.js
> +import { addHoursToDate } from '/Users/marionbelorgey/Desktop/MANO/mano/dashboard/src/services/date.js';
erreur d'import

2023-03-22 08:50 UTC, arnaudambro requested changes

2023-03-23 13:06 UTC, rap2hpoutre approved these changes
Je valide avec les trois notes que j'ai mises

2023-04-12 08:24 UTC, arnaudambro commented on dashboard/src/scenes/report/view.js
> +  const dateForSelector = addHoursToDate(date, '12');
pas besoin de cette abstraction
```suggestion
  const dateForSelector = dayjs(date).add(12, 'hour');
```

2023-04-21 12:24 UTC, arnaudambro approved these changes

2023-04-21 12:58 UTC, merged