fix: retreindre la création d'élément lorsqu'on commence le rechiffrement
SocialGouv/mano pull request #1457
Opened 2023-04-06 10:20 UTC by arnaudambro

- fix: retreindre la création d'élément lorsqu'on commence le rechiffrement

2023-04-11 07:39 UTC, rap2hpoutre requested changes
(mauvais bouton)

2023-04-21 13:14 UTC, arnaudambro commented
bonne idée pour le `ecnrypting`, effectivement on utilise pas le middleware pour les `GET` donc pas de problème

en revanche, on a une "faille": on utilise pas le middleware `validateEncryptionAndMigrations` pour les routes liées aux documents !

ce qui fait qu'utiliser `encrypting` fonctionne :)

2023-04-25 12:20 UTC, rap2hpoutre commented
DU coup je review ou pas ?

2023-05-23 13:07 UTC, arnaudambro commented
pas urgent

2023-05-23 13:07 UTC, closed without merging