fix(api): exclude sensitive data from user response
SocialGouv/mano pull request #147
Opened 2021-11-08 11:05 UTC by arnaudambro

2021-11-08 14:43 UTC, rap2hpoutre requested changes
Quand je me connecte avec cette PR j'ai cette erreur :

<img width="362" alt="Capture d’écran 2021-11-08 à 15 43 20" src="https://user-images.githubusercontent.com/1575946/140762308-7359693f-af42-4e4f-a66f-a13287e33951.png">

2021-11-10 13:36 UTC, arnaudambro commented
j'arrive pas à reproduire... t'es sûr ?

2021-11-11 16:33 UTC, rap2hpoutre commented
Fixé.

2021-11-11 16:34 UTC, rap2hpoutre approved these changes

2021-11-11 16:45 UTC, merged