Chore refacto recoil
SocialGouv/mano pull request #150
Opened 2021-11-09 10:08 UTC by arnaudambro

Objectifs: performance !
-> avec le `context`, il y a trop de re-renders qui affectent la performance, ce qui nous amène probablement à la limite de l'utilisation des `context` avec une sorte de store global

-> choix d'un autre type de state management: tentative avec Recoil

TODO
- [x] Refacto: enlever les contexts et mettre du Recoil à la place
- [ ] Vérifier les performances: optimiser le calcul des sélecteurs si besoins
- [ ] On avait fait le choix d'avoir des `personsFullPopulated` avec les actions et les commentaires à l'interieur, pour pouvoir faire une recherche sur l'ensemble des éléments liés à une personne : le calcul de ce sélector est plutôt long lorsqu'on ajoute/MAJ/supprime une personne / une action / un commentaire, ce qui peut faire lagguer l'app -> réfléchir à faire mieux (avoir un composant type preload, qui fait le calcul en masqué ?)
- [ ] Lors du téléchargement des commentaires par exemple, par batch de 1000, on veut pouvoir les afficher au fil de l'eau pour permettre à l'utilisateur de les voir arriver un par un MAIS ne veut pas faire le calcul du sélector à chaque fois, sinon ça rame

Donc ! Faut-il garder ces sélecteurs ? Probablement pas puisque ce sont seulement des sélecteurs pour faire une recherche, pas pour afficher

Faire mieux !

2021-11-09 19:33 UTC, arnaudambro commented
Bilan
-> moins de rerenders (test juste sur l'Accueil où au chargement, avec les context on a 36 rerenders, sans on a 26)
-> j'ai retiré les `machinFullPopulated` qui ne servaient que pour la recherche par mot clé et qui faisaient du calcul en permanence à chaque update de person/action/comment/etc. alors que finalement avec un selecteur certes un peu plus élaboré (https://github.com/SocialGouv/mano/blob/23e1e1055559f6e1d0e592881e833c3fcd00a771/dashboard/src/recoil/selectors.js#L104) on arrive au même résultat mais plus performant
-> j'ai ajouté un `useApi` parce que je pensais que c'était plus pratique d'avoir cet API contenue dans React pour tout ce qui est side effect (redirections au logout, erreurs, query avec organisationId etc.), mais j'ai une question: quand on met un `console.log` dans ce `useApi`, on constate qu'il est appelé des centaines de fois : il n'y a pas de render au bout donc pas de problème, mais est-ce que ça impacte la performance ? Je n'ai pas fait de test, et je ne me rends pas bien compte mentalement si ça peut être le cas où non, d'ailleurs j'ai l'impression que la question se pose avec chaque hook. Est-ce qu'un appel de fonction impacte la performance ?


Ce que j'ai laissé et qui peut ne pas plaire

-> abstraction, avec les `usePerson`, `useAction`: j'ai laissé parce que je ne vois pas de meilleure façon que de bien maintenir les side effects, et de le faire ET pour le dashboard, ET pour l'app (ex: https://github.com/SocialGouv/mano/blob/23e1e1055559f6e1d0e592881e833c3fcd00a771/dashboard/src/recoil/persons.js#L91). Je ne suis d'ailleurs pas certain que de maintenir ces abstractions sous forme de `useAbstraction` est une bonne idée : je me suis lancé dedans parce que c'était le plus simple avec tout ce qu'il y avait déjà à faire. À discuter !

-> `useApi` pour le dashboard (https://github.com/SocialGouv/mano/blob/23e1e1055559f6e1d0e592881e833c3fcd00a771/dashboard/src/services/api-interface-with-dashboard.js#L8), parce que je trouve que, étant donné l'encryption, c'est une bonne idée d'avoir un fichier api commun pour l'app et le dashboard. Mais je suis ouvert à changer si c'est pas beau !



Bref, c'est un premier énorme jet, qui marche bien, mais qu'on peut perfectionner, avec joie !

Désolé pour ce maxi gateau

2021-11-11 06:25 UTC, arnaudambro commented on dashboard/src/recoil/refresh.js
> +  const reportsRefresher = async (showFullScreen = false) => {
nouvelle méthode
pour bug fix: https://sentry.io/organizations/betagouv-f7/issues/2737486652/events/aef0c0bcfa9245728d96abbb63cf7ba8/?project=5833236&query=is%3Aunresolved+%21bookmarks%3Ame&statsPeriod=14d

2021-11-11 11:01 UTC, rap2hpoutre requested changes
C'est SUPER.

J'ai 2 petits bugs pour l'instant en testant le dashboard:
 - j’ai eu une erreur à la première tentative de connexionmais je reproduis plus. Le “role” de mon user était null
 - Je ne peux plus mettre à jour la sortie file active d'un user (ça marche sur main)

Sur mobile : 
 - Ajout d'une observation de territoire `TypeError: customFieldsObs.filter is not a function. (In 'customFieldsObs.filter(function (f) {`

C'est tout pour l'instant, je vais aussi relire le code.

2021-11-11 12:19 UTC, rap2hpoutre commented on dashboard/src/recoil/auth.js
> +  return { user, organisation, currentTeam, teams, users, setUsers, setUser, setOrganisation, setTeams, setCurrentTeam, organisationId };
Ici on voit qu'on a beaucoup de dépendances, pour finalement réexposer des fonctions et des listes, alors qu'on pourrait délier.

2021-11-11 12:29 UTC, rap2hpoutre reviewed
Bon j'avoue j'ai pas tout lu c'est un peu compliqué :D

2021-11-12 10:31 UTC, rap2hpoutre commented
Sur la page stats

<img width="1101" alt="Capture d’écran 2021-11-12 à 11 30 42" src="https://user-images.githubusercontent.com/1575946/141452641-314ee528-b942-4bd6-8572-d88e93107c30.png">

2021-11-12 11:07 UTC, arnaudambro commented
J'ai fixé la MAJ d'équipe (qui était probablement un bug de looooooongue date je pense)

Mais le reste je n'ai pas réussi à reproduire...

2021-11-12 12:55 UTC, merged