fix: customFields as object not string
SocialGouv/mano pull request #158
Opened 2021-11-12 14:38 UTC by rap2hpoutre

J'ai mis trèèèès longtemps avant de comprendre ce qui se passait.

En fait, pour une raison obscure, les `customFieldsObs` étaient stringuifiées. En résulte des opérations de stringification/déstringifications qui peuvent amener à des incohérence, car rien n'enmpèche de stringifier une chaine indéfiniement sans s'en rendre compte.

Du coup la solution porposée est de ne rien stringifier, vu que ce qu'on veut stocker c'est un objet et pas une chaine (les custom fields sont un array d'object, pas une chaine de caractères).

Le problème, c'est que comme actuellement les champs sont enregistrés en base de données pour les users (sauf pour moi je ne comprends pas pourquoi), il faut garder une sorte de rétrocompatibilité d'où mon if chelou. Si tu as mieux je prends. On pourrait aussi faire migrer tout le monde...

2021-11-12 15:00 UTC, arnaudambro commented on app/src/contexts/territoryObservations.js
> +  return (customFieldsObs = defaultCustomFields);
ça marche ça ? tout ce bloc qui finit par un `return` ?

2021-11-16 08:59 UTC, rap2hpoutre commented on app/src/contexts/territoryObservations.js
> +  return (customFieldsObs = defaultCustomFields);
Bien vu, résolu !!

2021-11-16 09:00 UTC, rap2hpoutre commented
Alors, après réflexion et suite à décision voilà ce que je propose : 
J'ai ajouté une migration pour les champs persos. Mais je garde aussi la rétrocompatibilité pour éviter une interruption de service. Je ferai un autre commit derrière pour effacer cette rétrocompatibilité, car elle sera inutile quelques minutes après el déploiement.

2021-11-16 10:07 UTC, arnaudambro requested changes

2021-11-16 10:07 UTC, arnaudambro commented on app/src/contexts/territoryObservations.js
> +  if (Array.isArray(organisation.custom_fields)) customFieldsObs = organisation.custom_fields;
```suggestion
  if (Array.isArray(organisation.customFieldsObs)) customFieldsObs = organisation.customFieldsObs;
```

2021-11-16 10:07 UTC, arnaudambro commented on dashboard/src/recoil/territoryObservations.js
> +    if (Array.isArray(organisation.custom_fields)) return organisation.custom_fields;
```suggestion
    if (Array.isArray(organisation.customFieldsObs)) return organisation.customFieldsObs;
```

2021-11-16 10:07 UTC, arnaudambro commented on dashboard/src/scenes/organisation/view.js
> +                          if (Array.isArray(organisation.custom_fields)) return organisation.custom_fields;
```suggestion
                          if (Array.isArray(organisation.customFieldsObs)) return organisation.customFieldsObs;
```

2021-11-16 10:26 UTC, merged