feat: pouvoir filtrer par actions créées le
SocialGouv/mano pull request #1869
Opened 2024-02-19 13:37 UTC by arnaudambro

2024-02-19 13:40 UTC, arnaudambro commented on dashboard/src/components/ActionModal.js
> +    if ([DONE, CANCEL].includes(data.status)) {
j'ai corrigé ce bug, qui consistait à avoir des `completedAt` non nuls même avec une action TODO
c'est le même comportement sur les consultations

2024-02-19 13:42 UTC, arnaudambro commented on dashboard/src/components/ActionModal.js
> +    if ([DONE, CANCEL].includes(data.status)) {
donc cette PR fait 2 choses différentes à la fois, tu peux me demander de virer ce correctif si tu veux, j'accepte par avance

2024-02-20 09:14 UTC, rap2hpoutre requested changes
Proposition alternative : https://github.com/mano-sesan/mano/pull/17

2024-02-20 10:38 UTC, rap2hpoutre commented
Remplacée : https://github.com/SocialGouv/mano/commit/93cdcd283532df6f10fe93170f723e0e9e7486db

2024-02-20 10:38 UTC, closed without merging