chore: remove code useless when all orgs have encryptedVerificationKey
SocialGouv/mano pull request #972
Opened 2022-11-13 11:05 UTC by arnaudambro

2022-11-14 13:36 UTC, arnaudambro commented on app/src/services/api.js
> +        capture('ERROR PARSING CONTENT', { extra: { errorDecryptParsing, content } });
je ne sais pas pourquoi il y avait seulement un `console.log` ici et pas un `capture`, mais c'est mieux `capture`
même si cette erreur ne devrait pas arriver, et n'est probablement pas encore arrivée

2022-11-14 13:37 UTC, arnaudambro commented on app/src/services/api.js
> +          hashedOrgEncryptionKey: this.hashedOrgEncryptionKey,
l'objectif ici, c'est de capturer temporairement cette donnée pour permettre de mieux débugger https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/61198/?project=52&query=is%3Aunresolved

2022-11-14 13:37 UTC, arnaudambro commented on app/src/services/api.js
> +          hashedOrgEncryptionKey: this.hashedOrgEncryptionKey,
discutable, of course

2022-11-15 10:40 UTC, rap2hpoutre requested changes
Super _mais je veux bien qu'on vire le truc sur la clé :)_

2022-11-15 10:40 UTC, rap2hpoutre commented on app/src/services/api.js
> +          hashedOrgEncryptionKey: this.hashedOrgEncryptionKey,
Donc idéalement : non :D

2022-11-15 14:57 UTC, arnaudambro commented
cleané, passé !

2022-11-18 14:17 UTC, merged